name: Listen to Project Repository

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch: 

jobs:
  check-external-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Local Repo
        uses: actions/checkout@v4

      - name: Fetch Remote Commit Hash
        id: remote
        run: |
          REMOTE_SHA=$(git ls-remote https://github.com/Shel-y/qintern2026-quantum-benchmarking main | awk '{print $1}')
          echo "latest_sha=$REMOTE_SHA" >> $GITHUB_OUTPUT
          echo "Current remote SHA is $REMOTE_SHA"

      - name: Restore Last Seen Hash Cache
        id: cache-lookup
        uses: actions/cache@v4
        with:
          path: .last_seen_sha
          key: external-sha-${{ steps.remote.outputs.latest_sha }}

      - name: Check for New Commits
        id: check-changes
        run: |
          if [ -f .last_seen_sha ]; then
            echo "No new changes detected since last run."
            echo "has_updates=false" >> $GITHUB_OUTPUT
          else
            echo "New commit detected! Updating cache marker..."
            echo "${{ steps.remote.outputs.latest_sha }}" > .last_seen_sha
            echo "has_updates=true" >> $GITHUB_OUTPUT
          fi

      - name: Save New Hash Cache
        if: steps.check-changes.outputs.has_updates == 'true'
        uses: actions/cache/save@v4
        with:
          path: .last_seen_sha
          key: external-sha-${{ steps.remote.outputs.latest_sha }}

      - name: Run My Custom Tasks
        if: steps.check-changes.outputs.has_updates == 'true'
        run: |
          curl -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2026-03-10" \
               "https://api.github.com/repos/Shel-y/https://github.com/Shel-y/qintern2026-quantum-benchmarking/commits/results/$(cat .last_seen_sha))" > .commit.json
     
      - name: Filter Commit File
        id: filter-commit
        run: |
          if [ -s .commit_txt ]; then
            if [ jq '.files.type .commit.json] == "png"; then
                  [ jq '.files.contents_url .commit.json ] > .content_url
                  curl -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2026-03-10" \
                  "https://api.github.com/repos/Shel-y/https://github.com/Shel-y/qintern2026-quantum-benchmarking/contents/$(cat .content_url)" > .graph.png
          else
              echo "The file $FILE is empty or does not exist."
          fi
               
               
               

               

               
          
